server:
  port: ${CART_SERVICE_PORT:8083}

spring:
  application:
    name: cart-service

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_SERVER_PORT:8761}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: ${JWT_SECRET:change-me-in-local-env-change-me-in-local-env-123456}

cart:
  ttl-seconds: ${CART_TTL_SECONDS:604800}

logging:
  level:
    root: INFO
    com.gokaycavdar: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] [corr=%X{correlationId}] %logger{36} - %msg%n"
